### ISSUE TITLE
GenericResponse's status reference may not be correct

### ISSUE THREAD

**Issue by kavehshahedi** [eclipse-cdt-cloud/tsp-python-client#77]
Hello,

As mentioned below, the `self.status` of `GenericResponse` is being assigned two times in a row. However, if I'm not mistaken, I think that the second reference value may be changed to something else like `self.status_text` since it is overwriting the assigned status. 

https://github.com/eclipse-cdt-cloud/tsp-python-client/blob/cb137c933746c38e06a1c248cd89df13efd2bf89/tsp/response.py#L103-L113

Here is the newly proposed code version:
```python
# Response status as described by ResponseStatus
if RESPONSE_STATUS_KEY in params:
    self.status = ResponseStatus(params.get(RESPONSE_STATUS_KEY))
else:  # pragma: no cover
    self.status = ResponseStatus.FAILED

# Message associated with the response
if STATUS_MESSAGE_KEY in params:
    self.status_text = params.get(STATUS_MESSAGE_KEY)
else:  # pragma: no cover
    self.status_text = ""
```

I'd be glad if you could verify this, and if it's already fine, briefly mention its logic.

Thanks,
Kaveh

**Comment by bhufmann** [comment]
I think it's a bug too, and your suggestion for code update makes sense. Thanks for reporting this.
